require("KikapuNvim.config.lazy")
require("KikapuNvim.config.cmp")
require("KikapuNvim.config.ibl")
require("KikapuNvim.config.lsp")
require("KikapuNvim.config.jinja")
-- require("KikapuNvim.config.linter")
